# TensorFlow Basic Syntex

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.4.1


In [4]:
hello = tf.constant("Hello ")

In [5]:
world = tf.constant("World")

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [9]:
print(result)

b'Hello World'


In [12]:
a = tf.constant(10)

In [11]:
b = tf.constant(20)

In [13]:
type(a)

tensorflow.python.framework.ops.Tensor

In [14]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [15]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [16]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [17]:
result

30

In [18]:
const = tf.constant(10)

In [19]:
fill_mat = tf.fill((4, 4), 10)

In [20]:
myzeros = tf.zeros((4, 4))

In [21]:
myones = tf.ones((4, 4))

In [25]:
myrandn = tf.random_normal((4, 4), mean=0, stddev=1.0)

In [26]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [24]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [27]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [28]:
sess = tf.InteractiveSession()

In [30]:
for op in my_ops:
#     print(sess.run(op))
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[-0.3977496   0.54134905 -1.11317241  2.33476448]
 [-0.28059855  0.22425459 -0.83714789 -0.13251473]
 [-0.93627143 -0.04093372  0.05483937 -0.52418625]
 [ 0.12599057  0.46603191 -1.46160102 -0.42647243]]


[[ 0.67381418  0.7618928   0.80398548  0.21412826]
 [ 0.22697163  0.12079585  0.99279904  0.75265443]
 [ 0.0251652   0.13780296  0.76240206  0.31642401]
 [ 0.70703042  0.55063653  0.02951181  0.40726364]]




In [31]:
a = tf.constant([ [1,2],
                  [3, 4] ])

In [33]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [34]:
b = tf.constant([[10], [100]])

In [35]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [36]:
result = tf.matmul(a, b)

In [37]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [38]:
result.eval()

array([[210],
       [430]], dtype=int32)